[template]
src = "salesforce-fetcher.tmpl"
dest = "/opt/etl/salesforce/fetch.yml"
prefix = "/%%PROJECT%%-%%ENVIRONMENT%%/%%ENVIRONMENT%%"

uid = 0
gid = 0
mode = "0644"

keys = [
    "/config/*",
    "/config"
]
