[template]
src = "sfmc-fetcher.tmpl"
dest = "/opt/etl/salesforce_sfmc/secrets_brickftp.py"
prefix = "/%%PROJECT%%-%%ENVIRONMENT%%/%%ENVIRONMENT%%"

uid = 0
gid = 0
mode = "0644"

keys = [
    "/config/*",
    "/config"
]
