[template]
src = "secrets_util.py.tmpl"
dest = "/usr/local/virtualenvs/data-integrations/lib64/python3.4/site-packages/Util/secrets_util.py"
prefix = "/%%PROJECT%%-%%ENVIRONMENT%%/%%ENVIRONMENT%%"

uid = 0
gid = 0
mode = "0644"

keys = [
    "/config/*",
    "/config"
]
