[template]
src = "workday-plus.py.tmpl"
dest = "/opt/etl/workday/fetch_plus_config.py"
prefix = "/%%PROJECT%%-%%ENVIRONMENT%%/%%ENVIRONMENT%%"

uid = 0
gid = 0
mode = "0644"

keys = [
    "/config/*",
    "/config"
]
