[template]
src = "secrets_workday.tmpl"
dest = "/usr/local/virtualenvs/data-integrations/Workday/secrets_workday.py"
prefix = "/%%PROJECT%%-%%ENVIRONMENT%%/%%ENVIRONMENT%%"

uid = 0
gid = 0
mode = "0644"

keys = [
    "/config/*",
    "/config"
]
